import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import { headerConfig } from '@/config';

import { Header } from '@/components/Header';
import { Layout } from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary text-gray-50`}>
        <Header items={headerConfig} />
        <Layout>
          <div className="pt-20">{children}</div>
        </Layout>
      </body>
    </html>
  );
}
